// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShopApi.Data;

#nullable disable

namespace ShopApi.Migrations
{
    [DbContext(typeof(ShopContext))]
    [Migration("20260417021752_AddOrdersTable")]
    partial class AddOrdersTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("ShopApi.Models.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("ShopApi.Models.Favorite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Favorites");
                });

            modelBuilder.Entity("ShopApi.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("ShopApi.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Winter",
                            CreatedAt = new DateTime(2026, 4, 17, 2, 17, 49, 698, DateTimeKind.Utc).AddTicks(7230),
                            Description = "Trendy streetwear hoodie floating in mid-air.",
                            ImageUrl = "assets/images/premium_3d_hoodie.png",
                            Name = "Premium 3D Hoodie",
                            Price = 120.00m
                        },
                        new
                        {
                            Id = 2,
                            Category = "Summer",
                            CreatedAt = new DateTime(2026, 4, 17, 2, 17, 49, 698, DateTimeKind.Utc).AddTicks(7546),
                            Description = "A pair of premium, futuristic trendy sneakers.",
                            ImageUrl = "assets/images/premium_3d_sneakers.png",
                            Name = "Futuristic Sneakers",
                            Price = 250.00m
                        },
                        new
                        {
                            Id = 3,
                            Category = "Winter",
                            CreatedAt = new DateTime(2026, 4, 17, 2, 17, 49, 698, DateTimeKind.Utc).AddTicks(7549),
                            Description = "Premium, stylish modern jacket or puffer coat.",
                            ImageUrl = "assets/images/premium_3d_jacket.png",
                            Name = "Modern Puffer Jacket",
                            Price = 340.00m
                        },
                        new
                        {
                            Id = 4,
                            Category = "Summer",
                            CreatedAt = new DateTime(2026, 4, 17, 2, 17, 49, 698, DateTimeKind.Utc).AddTicks(7551),
                            Description = "Lightweight vintage-style summer shirt.",
                            ImageUrl = "https://images.unsplash.com/photo-1576566588028-4147f3842f27?q=80&w=800",
                            Name = "Summer Vintage Shirt",
                            Price = 65.00m
                        },
                        new
                        {
                            Id = 5,
                            Category = "Summer",
                            CreatedAt = new DateTime(2026, 4, 17, 2, 17, 49, 698, DateTimeKind.Utc).AddTicks(7553),
                            Description = "Premium streetwear cargo shorts.",
                            ImageUrl = "https://images.unsplash.com/photo-1591195853828-11db59a44f6b?q=80&w=800",
                            Name = "Cargo Shorts",
                            Price = 90.00m
                        },
                        new
                        {
                            Id = 6,
                            Category = "Summer",
                            CreatedAt = new DateTime(2026, 4, 17, 2, 17, 49, 698, DateTimeKind.Utc).AddTicks(7555),
                            Description = "Trendy summer bucket hat.",
                            ImageUrl = "https://images.unsplash.com/photo-1521369909029-2afed882ba54?q=80&w=800",
                            Name = "Streetwear Bucket Hat",
                            Price = 45.00m
                        },
                        new
                        {
                            Id = 7,
                            Category = "Winter",
                            CreatedAt = new DateTime(2026, 4, 17, 2, 17, 49, 698, DateTimeKind.Utc).AddTicks(7557),
                            Description = "Warm winter knit beanie cap.",
                            ImageUrl = "https://images.unsplash.com/photo-1576871337622-98d48d1cf531?q=80&w=800",
                            Name = "Winter Knit Beanie",
                            Price = 35.00m
                        },
                        new
                        {
                            Id = 8,
                            Category = "Winter",
                            CreatedAt = new DateTime(2026, 4, 17, 2, 17, 49, 698, DateTimeKind.Utc).AddTicks(7559),
                            Description = "Heavy duty tactical winter boots.",
                            ImageUrl = "https://images.unsplash.com/photo-1520639888713-7851133b1ed0?q=80&w=800",
                            Name = "Tactical Winter Boots",
                            Price = 210.00m
                        },
                        new
                        {
                            Id = 9,
                            Category = "Winter",
                            CreatedAt = new DateTime(2026, 4, 17, 2, 17, 49, 698, DateTimeKind.Utc).AddTicks(7560),
                            Description = "Premium soft designer scarf.",
                            ImageUrl = "https://images.unsplash.com/photo-1601379430166-70eeb04e2808?q=80&w=800",
                            Name = "Designer Scarf",
                            Price = 110.00m
                        });
                });

            modelBuilder.Entity("ShopApi.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PasswordHash = "$2a$11$Boa/Pk8wPqSRRBomUvYOGOetW.zOSc7VpIyISQt9n/VxXa8kKXwEG",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("ShopApi.Models.CartItem", b =>
                {
                    b.HasOne("ShopApi.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ShopApi.Models.Favorite", b =>
                {
                    b.HasOne("ShopApi.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });
#pragma warning restore 612, 618
        }
    }
}
